version: '3'
services:
  exoscale-circleci-nodejs:
    build: .
    image: tribaal/exoscale-circleci-nodejs:latest
    ports:
      - "80:3000"
    environment:
      - APP_VERSION=$APP_VERSION
    container_name: node_app
